/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.login;

import controller.account_controller.AccountController;
import java.util.Arrays;
/**
 *
 * @author huant
 */
import view.dashboard.AdminDashboard;
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        AccountController controller=new AccountController(this,btnSubmit,jtfUsername,jpfPassword,jlbMsg);  
        controller.setEvent();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jtfUsername = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnSubmit = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jlbMsg = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jpnRoot.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 255));
        jPanel2.setForeground(new java.awt.Color(0, 102, 255));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 333, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );

        jpnRoot.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 430));

        jtfUsername.setText("Username");
        jtfUsername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtfUsernameMouseClicked(evt);
            }
        });
        jtfUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfUsernameActionPerformed(evt);
            }
        });
        jpnRoot.add(jtfUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(469, 156, 180, 30));

        jpfPassword.setText("jPasswordField1");
        jpfPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jpfPasswordMouseClicked(evt);
            }
        });
        jpfPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpfPasswordActionPerformed(evt);
            }
        });
        jpnRoot.add(jpfPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 180, 30));

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 255));
        jLabel1.setText("Boarding Management");
        jpnRoot.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 10, -1, -1));

        btnSubmit.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        btnSubmit.setText("Login");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });
        jpnRoot.add(btnSubmit, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 280, -1, -1));

        jLabel4.setFont(new java.awt.Font("Yu Gothic UI", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 102, 255));
        jLabel4.setText("Login");
        jpnRoot.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 70, -1, -1));

        jSeparator1.setPreferredSize(new java.awt.Dimension(50, 20));
        jpnRoot.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 103, 180, 10));

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_person_black_24dp.png"))); // NOI18N
        jpnRoot.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 40, -1));

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI", 1, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_lock_black_24dp.png"))); // NOI18N
        jpnRoot.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 40, -1));

        jlbMsg.setFont(new java.awt.Font("Microsoft New Tai Lue", 1, 12)); // NOI18N
        jlbMsg.setForeground(new java.awt.Color(255, 0, 0));
        jpnRoot.add(jlbMsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        getContentPane().add(jpnRoot, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 720, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jpfPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpfPasswordActionPerformed
        
    }//GEN-LAST:event_jpfPasswordActionPerformed

    private void jtfUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfUsernameActionPerformed
       
    }//GEN-LAST:event_jtfUsernameActionPerformed

    private void jtfUsernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtfUsernameMouseClicked
        // TODO add your handling code here:
         jtfUsername.setText("");
    }//GEN-LAST:event_jtfUsernameMouseClicked

    private void jpfPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jpfPasswordMouseClicked
        // TODO add your handling code here:
        jpfPassword.setText("");
    }//GEN-LAST:event_jpfPasswordMouseClicked

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed
        // TODO add your handling code here:
//        if (jtfUsername.getText().equals("admin") && Arrays.equals(jpfPassword.getPassword(), "123".toCharArray())) {
//        new AdminDashboard().setVisible(true);
//}

    }//GEN-LAST:event_btnSubmitActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSubmit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel jlbMsg;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JTextField jtfUsername;
    // End of variables declaration//GEN-END:variables
}
