/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.dashboard;

import controller.ChuyenManHinh.ChuyenManHinh;
import controller.dashboard_controller.DanhMucBean;

import java.util.ArrayList;
import java.util.List;
/**
 *
 * @author huant
 */
public class AdminDashboard extends javax.swing.JFrame {

    /**
     * Creates new form AdminDashboard1
     */
    public AdminDashboard() {
        initComponents();
        setTitle("Boarding Management");
        
        ChuyenManHinh controller = new ChuyenManHinh(jpnView);
        controller.setView(jpnMain,jlbMain);
        List<DanhMucBean> listItem=new ArrayList<>();
        listItem.add(new DanhMucBean("Main",jpnMain,jlbMain));
        listItem.add(new DanhMucBean("Teacher",jpnTeacher,jlbTeacher));
        listItem.add(new DanhMucBean("Pupil",jpnPupil,jlbPupil));
        listItem.add(new DanhMucBean("Class",jpnClass,jlbClass));
        listItem.add(new DanhMucBean("BoardingRoom",jpnBoardingRoom,jlbBoardingRoom));
        listItem.add(new DanhMucBean("Payment",jpnPayment,jlbPayment));
        listItem.add(new DanhMucBean("Info",jpnInfo,jlbInfo));
        controller.setEvent(listItem);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnView = new javax.swing.JPanel();
        jpMenu = new javax.swing.JPanel();
        jpnMain = new javax.swing.JPanel();
        jlbMain = new javax.swing.JLabel();
        jlbTeacher1 = new javax.swing.JLabel();
        jpnTeacher = new javax.swing.JPanel();
        jlbTeacher = new javax.swing.JLabel();
        jpnBoardingRoom = new javax.swing.JPanel();
        jlbBoardingRoom = new javax.swing.JLabel();
        jpnClass = new javax.swing.JPanel();
        jlbClass = new javax.swing.JLabel();
        jpnPupil = new javax.swing.JPanel();
        jlbPupil = new javax.swing.JLabel();
        jpnPayment = new javax.swing.JPanel();
        jlbPayment = new javax.swing.JLabel();
        jpnInfo = new javax.swing.JPanel();
        jlbInfo = new javax.swing.JLabel();
        jlbLogOut = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1500, 765));
        setPreferredSize(new java.awt.Dimension(1500, 765));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1210, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jpMenu.setBackground(new java.awt.Color(74, 188, 253));

        jpnMain.setBackground(new java.awt.Color(255, 255, 255));

        jlbMain.setFont(new java.awt.Font("Segoe UI Black", 1, 18)); // NOI18N
        jlbMain.setText("Boarding Management");

        jlbTeacher1.setBackground(new java.awt.Color(238, 238, 228));
        jlbTeacher1.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlbTeacher1.setForeground(new java.awt.Color(153, 153, 153));
        jlbTeacher1.setText("Hi, Admin");

        javax.swing.GroupLayout jpnMainLayout = new javax.swing.GroupLayout(jpnMain);
        jpnMain.setLayout(jpnMainLayout);
        jpnMainLayout.setHorizontalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMainLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jlbTeacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlbMain))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMainLayout.setVerticalGroup(
            jpnMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMainLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbMain, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbTeacher1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jpnTeacher.setBackground(new java.awt.Color(0, 153, 255));

        jlbTeacher.setBackground(new java.awt.Color(238, 238, 228));
        jlbTeacher.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlbTeacher.setForeground(new java.awt.Color(238, 238, 228));
        jlbTeacher.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/teacher (1).png"))); // NOI18N
        jlbTeacher.setText("Manage Teacher");

        javax.swing.GroupLayout jpnTeacherLayout = new javax.swing.GroupLayout(jpnTeacher);
        jpnTeacher.setLayout(jpnTeacherLayout);
        jpnTeacherLayout.setHorizontalGroup(
            jpnTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTeacherLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jlbTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jpnTeacherLayout.setVerticalGroup(
            jpnTeacherLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnTeacherLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(jlbTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        jpnBoardingRoom.setBackground(new java.awt.Color(0, 153, 255));

        jlbBoardingRoom.setBackground(new java.awt.Color(238, 238, 228));
        jlbBoardingRoom.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlbBoardingRoom.setForeground(new java.awt.Color(238, 238, 228));
        jlbBoardingRoom.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/restaurant.png"))); // NOI18N
        jlbBoardingRoom.setText("Manage Boarding Room");

        javax.swing.GroupLayout jpnBoardingRoomLayout = new javax.swing.GroupLayout(jpnBoardingRoom);
        jpnBoardingRoom.setLayout(jpnBoardingRoomLayout);
        jpnBoardingRoomLayout.setHorizontalGroup(
            jpnBoardingRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBoardingRoomLayout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jlbBoardingRoom)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnBoardingRoomLayout.setVerticalGroup(
            jpnBoardingRoomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnBoardingRoomLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jlbBoardingRoom, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jpnClass.setBackground(new java.awt.Color(0, 153, 255));

        jlbClass.setBackground(new java.awt.Color(238, 238, 228));
        jlbClass.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlbClass.setForeground(new java.awt.Color(238, 238, 228));
        jlbClass.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/classroom-32.png"))); // NOI18N
        jlbClass.setText("Manage Class");

        javax.swing.GroupLayout jpnClassLayout = new javax.swing.GroupLayout(jpnClass);
        jpnClass.setLayout(jpnClassLayout);
        jpnClassLayout.setHorizontalGroup(
            jpnClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnClassLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addComponent(jlbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnClassLayout.setVerticalGroup(
            jpnClassLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnClassLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jlbClass, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        jpnPupil.setBackground(new java.awt.Color(0, 153, 255));

        jlbPupil.setBackground(new java.awt.Color(238, 238, 228));
        jlbPupil.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlbPupil.setForeground(new java.awt.Color(238, 238, 228));
        jlbPupil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/student_little_boy.png"))); // NOI18N
        jlbPupil.setText("Manage Pupil");

        javax.swing.GroupLayout jpnPupilLayout = new javax.swing.GroupLayout(jpnPupil);
        jpnPupil.setLayout(jpnPupilLayout);
        jpnPupilLayout.setHorizontalGroup(
            jpnPupilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPupilLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jlbPupil, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnPupilLayout.setVerticalGroup(
            jpnPupilLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPupilLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbPupil, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jpnPayment.setBackground(new java.awt.Color(0, 153, 255));

        jlbPayment.setBackground(new java.awt.Color(238, 238, 228));
        jlbPayment.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlbPayment.setForeground(new java.awt.Color(238, 238, 228));
        jlbPayment.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/wallet.png"))); // NOI18N
        jlbPayment.setText("Manage Payment");

        javax.swing.GroupLayout jpnPaymentLayout = new javax.swing.GroupLayout(jpnPayment);
        jpnPayment.setLayout(jpnPaymentLayout);
        jpnPaymentLayout.setHorizontalGroup(
            jpnPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPaymentLayout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jlbPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnPaymentLayout.setVerticalGroup(
            jpnPaymentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnPaymentLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jlbPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jpnInfo.setBackground(new java.awt.Color(0, 153, 255));

        jlbInfo.setBackground(new java.awt.Color(238, 238, 228));
        jlbInfo.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlbInfo.setForeground(new java.awt.Color(238, 238, 228));
        jlbInfo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/information.png"))); // NOI18N
        jlbInfo.setText("Change Information");

        javax.swing.GroupLayout jpnInfoLayout = new javax.swing.GroupLayout(jpnInfo);
        jpnInfo.setLayout(jpnInfoLayout);
        jpnInfoLayout.setHorizontalGroup(
            jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpnInfoLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        jpnInfoLayout.setVerticalGroup(
            jpnInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnInfoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jlbInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        jlbLogOut.setBackground(new java.awt.Color(238, 238, 228));
        jlbLogOut.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jlbLogOut.setForeground(new java.awt.Color(238, 238, 228));
        jlbLogOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logout.png"))); // NOI18N
        jlbLogOut.setText("Log Out");

        javax.swing.GroupLayout jpMenuLayout = new javax.swing.GroupLayout(jpMenu);
        jpMenu.setLayout(jpMenuLayout);
        jpMenuLayout.setHorizontalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jpnTeacher, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnPupil, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(5, 5, 5))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                        .addComponent(jpnBoardingRoom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                        .addComponent(jpnClass, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                        .addGroup(jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jpnPayment, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jpnInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpMenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jlbLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jpMenuLayout.setVerticalGroup(
            jpMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpMenuLayout.createSequentialGroup()
                .addComponent(jpnMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnTeacher, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnPupil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnClass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnBoardingRoom, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnPayment, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jlbLogOut, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(93, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jpnView, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminDashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminDashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbBoardingRoom;
    private javax.swing.JLabel jlbClass;
    private javax.swing.JLabel jlbInfo;
    private javax.swing.JLabel jlbLogOut;
    private javax.swing.JLabel jlbMain;
    private javax.swing.JLabel jlbPayment;
    private javax.swing.JLabel jlbPupil;
    private javax.swing.JLabel jlbTeacher;
    private javax.swing.JLabel jlbTeacher1;
    private javax.swing.JPanel jpMenu;
    private javax.swing.JPanel jpnBoardingRoom;
    private javax.swing.JPanel jpnClass;
    private javax.swing.JPanel jpnInfo;
    private javax.swing.JPanel jpnMain;
    private javax.swing.JPanel jpnPayment;
    private javax.swing.JPanel jpnPupil;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTeacher;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
