/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.dashboard.pupil_dashboard;

import java.awt.image.BufferedImage;
import java.sql.SQLException;

import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JButton;

import controller.dashboard_controller.pupil_dashboard_controller.AbsenceRegisterController;
import model.account.Account;

/**
 *
 * @author Lenovo
 */
public class AbsenceRegister extends javax.swing.JPanel {
    /**
     * Creates new form AbsenceRegister
     */
    Account account;
    private AbsenceRegisterController controller;
    private final int ROW = 5;
    private final int COL = 7;
    private JButton[][] calendarCell = new JButton[ROW + 1][COL + 1];

    public AbsenceRegister(Account account) throws ClassNotFoundException, SQLException {
        this.account = account;
        initComponents();
        customInit();
        controller = new AbsenceRegisterController(account, calendarCell, changeMonthYearDataLabel, monthChooserTextField, yearChooserTextField, currentMonthInformationLabel);
        controller.loadCalendar();
        controller.setEvent();
    }

    void customInit() {
        try {
            BufferedImage img = ImageIO.read(getClass().getResource("/images/reload_icon.png"));
            changeMonthYearDataLabel.setIcon(new ImageIcon(img));
        } catch (Exception e) {e.printStackTrace();}
        for (int i = 0; i <= ROW; i ++)
            for (int j = 1; j <= COL; j ++) {
                calendarCell[i][j] = new JButton();
                this.add(calendarCell[i][j]);
            }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        currentMonthInformationLabel = new javax.swing.JLabel();
        chooseAnotherMonthLabel = new javax.swing.JLabel();
        monthChooserTextField = new javax.swing.JTextField();
        minusSignLabel = new javax.swing.JLabel();
        yearChooserTextField = new javax.swing.JTextField();
        changeMonthYearDataLabel = new javax.swing.JLabel();

        currentMonthInformationLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        currentMonthInformationLabel.setText("currentMonthInformationLabel");

        chooseAnotherMonthLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        chooseAnotherMonthLabel.setText("Or you can choose another month/year");

        monthChooserTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        minusSignLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        minusSignLabel.setText("/");

        yearChooserTextField.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        yearChooserTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearChooserTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(currentMonthInformationLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chooseAnotherMonthLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthChooserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(minusSignLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(yearChooserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(changeMonthYearDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(209, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(currentMonthInformationLabel)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(minusSignLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(yearChooserTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(chooseAnotherMonthLabel))
                            .addComponent(monthChooserTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(changeMonthYearDataLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(418, Short.MAX_VALUE))
        );

        monthChooserTextField.getAccessibleContext().setAccessibleDescription("");
    }// </editor-fold>//GEN-END:initComponents

    private void yearChooserTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearChooserTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yearChooserTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel changeMonthYearDataLabel;
    private javax.swing.JLabel chooseAnotherMonthLabel;
    private javax.swing.JLabel currentMonthInformationLabel;
    private javax.swing.JLabel minusSignLabel;
    private javax.swing.JTextField monthChooserTextField;
    private javax.swing.JTextField yearChooserTextField;
    // End of variables declaration//GEN-END:variables
}
