package view.dashboard.pupil_dashboard;

import java.sql.SQLException;
import java.time.LocalDate;

import javax.swing.JButton;

import constant.AvailableMonth;
import controller.dashboard_controller.pupil_dashboard_controller.PaymentController;
import model.account.Account;

public class PaymentPanel extends javax.swing.JPanel {
    private PaymentController controller;
    private Account account;
    private JButton[] statusButton = new JButton[10];
    /**
     * Creates new form PaymentPanel
     * @throws SQLException 
     * @throws ClassNotFoundException 
     */
    public PaymentPanel(Account account) throws ClassNotFoundException, SQLException {
        this.account = account;
        initComponents();
        customInit();
        controller = new PaymentController(account, stateLabel, needToPayLabel, hasPaidLabel, payBackLabel, monthChooser, statusButton);
    }

    private void customInit() {
        for (int i = 1; i <= 9; i ++) {
            statusButton[i] = new JButton();
            this.add(statusButton[i]);
        }
        for (int i = 0; i < AvailableMonth.month.size(); i ++) monthChooser.addItem(AvailableMonth.month.get(i));
        for (int i = 0; i < AvailableMonth.month.size(); i ++) 
            if (LocalDate.now().getMonthValue() == AvailableMonth.date.get(i).getMonthValue())
                monthChooser.setSelectedIndex(i);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        paymentInformationLabel = new javax.swing.JLabel();
        monthChooserLabel = new javax.swing.JLabel();
        monthChooser = new javax.swing.JComboBox<>();
        stateLabel = new javax.swing.JLabel();
        needToPayLabel = new javax.swing.JLabel();
        hasPaidLabel = new javax.swing.JLabel();
        payBackLabel = new javax.swing.JLabel();
        informationLabel = new javax.swing.JLabel();

        paymentInformationLabel.setFont(new java.awt.Font("Arial", 1, 30)); // NOI18N
        paymentInformationLabel.setText("Payment Information");

        monthChooserLabel.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        monthChooserLabel.setText("You are currently view payment information in");

        monthChooser.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        stateLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        needToPayLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        hasPaidLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        payBackLabel.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        informationLabel.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        informationLabel.setText("Information:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(informationLabel)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(payBackLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 550, Short.MAX_VALUE)
                        .addComponent(hasPaidLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(needToPayLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(stateLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(paymentInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(monthChooserLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(monthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(599, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(paymentInformationLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(monthChooserLabel)
                    .addComponent(monthChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(informationLabel)
                .addGap(18, 18, 18)
                .addComponent(stateLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(needToPayLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(hasPaidLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(payBackLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel hasPaidLabel;
    private javax.swing.JLabel informationLabel;
    private javax.swing.JComboBox<String> monthChooser;
    private javax.swing.JLabel monthChooserLabel;
    private javax.swing.JLabel needToPayLabel;
    private javax.swing.JLabel payBackLabel;
    private javax.swing.JLabel paymentInformationLabel;
    private javax.swing.JLabel stateLabel;
    // End of variables declaration//GEN-END:variables
}
