/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view.dashboard.teacher_dashboard;

import java.sql.SQLException;
import java.time.LocalDate;

import controller.dashboard_controller.teacher_dashboard_controller.AbsenceRegisterController;
import model.account.Account;
import model.classroom.Classroom;

/**
 *
 * @author Lenovo
 */
public class AbsenceRegisterPanel extends javax.swing.JPanel {
    private ClassroomPanel classroomPanel;
    /**
     * Creates new form AbsenceRegister
     * @throws SQLException 
     * @throws ClassNotFoundException 
     */
    public AbsenceRegisterPanel(Classroom classroom,Account account) throws ClassNotFoundException, SQLException {
        initComponents();
        classroomPanel = new ClassroomPanel(classroom,account);
        classroomPanel.setSize(1500, 800);
        this.add(classroomPanel);
        AbsenceRegisterController controller = new AbsenceRegisterController(classroomPanel, registerAbsenceButton);
        controller.setEvent();
        jLabel1.setText("Today is: " + LocalDate.now().toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        registerAbsenceButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        registerAbsenceButton.setBackground(new java.awt.Color(51, 255, 255));
        registerAbsenceButton.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        registerAbsenceButton.setText("Register Absence Today");

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(registerAbsenceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(652, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(registerAbsenceButton, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(63, 63, 63))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton registerAbsenceButton;
    // End of variables declaration//GEN-END:variables
}
